# Generated by Django 2.1.7 on 2019-03-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creditHours',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='termNum',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
