# Generated by Django 2.2 on 2019-05-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20190301_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lecExDay',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='lecExFrom',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='lecExPlace',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='lecExTo',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
