# Generated by Django 2.2 on 2019-09-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20190922_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExPlace', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('ExDay', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('ExFrom', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('ExTo', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='ExPlace',
        ),
        migrations.RemoveField(
            model_name='time',
            name='ExDay',
        ),
        migrations.RemoveField(
            model_name='time',
            name='ExFrom',
        ),
        migrations.RemoveField(
            model_name='time',
            name='ExTo',
        ),
    ]
