# Generated by Django 2.2 on 2019-09-22 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20190922_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='exlecture',
            name='lecture',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Lecture'),
        ),
    ]
