# Generated by Django 2.2 on 2019-09-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_exlecture_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
