# Generated by Django 2.2 on 2019-09-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_group_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
