# Generated by Django 2.2 on 2019-09-22 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20190922_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='exlecture',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.ExLecture'),
        ),
    ]
