# Generated by Django 2.2 on 2019-09-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_time_exlecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exlecture',
            name='ExDay',
        ),
        migrations.RemoveField(
            model_name='exlecture',
            name='ExFrom',
        ),
        migrations.RemoveField(
            model_name='exlecture',
            name='ExTo',
        ),
    ]
