# Generated by Django 2.2 on 2019-09-22 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20190922_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exlecture',
            old_name='ExPlace',
            new_name='Place',
        ),
    ]
