# Generated by Django 2.2 on 2019-05-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_group_credithours'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='groupNum',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
