# Generated by Django 2.2 on 2019-05-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_group_lecfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lecTo',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
