# Generated by Django 2.2 on 2019-05-21 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_auto_20190521_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='lecExDay',
        ),
        migrations.RemoveField(
            model_name='group',
            name='lecExFrom',
        ),
        migrations.RemoveField(
            model_name='group',
            name='lecExPlace',
        ),
        migrations.RemoveField(
            model_name='group',
            name='lecExTo',
        ),
    ]
