# Generated by Django 2.2 on 2019-05-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0031_group_tut1from'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tut1To',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
