# Generated by Django 2.2 on 2019-05-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0054_group_lab2day'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lab2From',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
