# Generated by Django 2.2 on 2019-09-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0057_group_lab2periodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
