# Generated by Django 2.2 on 2019-09-20 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0058_group_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instName', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('courseName', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('instID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Instructor')),
            ],
        ),
    ]
