# Generated by Django 2.2 on 2019-09-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0059_course_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseName',
            new_name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='priority',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='priority',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
