# Generated by Django 2.2 on 2019-09-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0060_auto_20190920_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instID',
            new_name='inst',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='groupID',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='instName',
            new_name='name',
        ),
    ]
